### ISSUE TITLE
操作系统第二大组，小组选题

### ISSUE THREAD

**Issue by sunziping2016** [sunziping2016/xv6-improved#2]
#如题

注意，issue也是未来我们交流bug、feature以及组间沟通的重要地方。

还有些组可以做一下内核优化、以及学长代码迁移的工作。

另外，大家放心，**我一定会综合考虑难度和工作量，去评价大家的工作成果的！**

**Comment by sunziping2016** [comment]
我们组做 C 语言标准库的迁移。外加一些内核的优化，系统底层的实现（中断向量表等等）

**Comment by zerotrac** [comment]
龙神表示随机选一个 那就选文件系统好了

**Comment by matinjugou** [comment]
黄超组：socket

**Comment by WanDanLou** [comment]
李金明组:Devfs 设备文件

**Comment by thsshz** [comment]
胡哲组：信号

**Comment by teleportor** [comment]
焦子南组：多线程

**Comment by aglax2357** [comment]
朱泓宇组 Shell

**Comment by thss15fyt** [comment]
冯玉彤组：Procfs 虚拟文件系统

**Comment by yuanjunyj** [comment]
吉书仪组：shell

**Comment by ZTWAPPLE** [comment]
张天玮组：多线程
